### PR TITLE
master to main rename

### PR DESCRIPTION
**Pull request by ikarldasan**
**What this PR does / why we need it**:
Needed for kubernetes/k8s.io#1597

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Needed for kubernetes/k8s.io#1597

### CODE REVIEW

**Review by nilekhc — APPROVED** [review]

**Comment by tam7t** [comment]
/ok-to-test

Thanks for the PR, I've created https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/617 as well to track migrating this repo

**Review by tam7t — APPROVED** [review]

**Comment by tam7t** [comment]
Failures seem to be repeated and unrelated to the change. Created https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/619 to track/fix

**Pull request merged**
