### PR TITLE
Allow the 'updateStrategy' of the Daemonset to be configured in Helm

### LINKED ISSUE #361: Support configuring updateStrategy.rollingUpdate.maxUnavailable in Helm charts
**Describe the solution you'd like**
Right now the Helm Chart configure the Daemonset with the RollingUpdate strategy, but don't provide any option so specify the 'maxUnavailble' property, so the default value of '1' is being used. On our 60+ node clusters this is causing the deployment to take 40+ minutes to complete. It would be great if the Helm charts allowed 'maxUnavailable' to be configurable so more than one node can be updated at once.

**Anything else you would like to add:**
Related issue in the KeyVault Provider repo: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/283

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

### PR DESCRIPTION
**Pull request by chrisamert**
**What this PR does / why we need it**:
This PR enables the 'updateStrategy' of the Daemonset to be configured by Helm parameters.  This has two different parameters, one for Linux and one for Windows, following the existing pattern for these variables.  The default values are the same as the current defaults; RollingUpdate strategy with maxUnavailable set to 1, so behavior will change only if the user specifies a custom value.

**Which issue(s) this PR fixes**:
Fixes #361

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aramase — CHANGES_REQUESTED** [review]
@chrisamert These changes need to be made in the `manifest_staging` dir where we currently host the staging charts. All the chart changes are then tagged with the release. Could you make the changes only in [manifest_staging/charts](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/manifest_staging/charts/secrets-store-csi-driver) instead

**Comment by chrisamert** [comment]
I missed that, I'll get them moved over

**Comment by aramase** [comment]
thank you @chrisamert. Could you also sign the CLA - https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/362#issuecomment-715526292.

**Comment by chrisamert** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

I've signed the CLA here

**Comment by aramase** [comment]
Adding the default values from docs here for future reference-

```
RollingUpdate: This is the default update strategy.
With RollingUpdate update strategy, after you update a DaemonSet template, old DaemonSet pods will be killed, and new DaemonSet pods will be created automatically, in a controlled fashion. At most one pod of the DaemonSet will be running on each node during the whole update process.
```

```
You may want to set .spec.updateStrategy.rollingUpdate.maxUnavailable (default to 1) and .spec.minReadySeconds (default to 0) as well.
```

Ref docs:
https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#daemonset-update-strategy
https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#performing-a-rolling-update

**Review by aramase — COMMENTED** [review]
/lgtm

**Pull request merged**
