### PR TITLE
move cleanup of eks cluster to cleanup_file

### PR DESCRIPTION
**Pull request by lasred**
**What this PR does / why we need it**:

To ensure cleanup of eks cluster happens regardless of the tests pass or fail 

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/634

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tam7t** [comment]
The aws test error looks real:

```
make: *** No rule to make target 'e2e-eks-cleanup'.  Stop.
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker.
```

You may need to keep the target but make it a noop, remove it from https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/secrets-store-csi-driver/secrets-store-csi-driver-config.yaml then remove the target

**Comment by lasred** [comment]
yup @tam7t I removed it from test-infra yaml file - https://github.com/kubernetes/test-infra/pull/22920

**Pull request closed without merging**
