### PR TITLE
[WIP] feat: compute SHA for data and patch if data changed

### PR DESCRIPTION
**Pull request by aramase**
**What this PR does / why we need it**:
- Generates `SHA` for existing secret data and expected secret data. If the SHA doesn't match, then replace the contents with the expected content. This ensures when pods are deleted by `RollingUpdate` but secret isn't deleted, then the contents are kept up to date. 

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by connor4312** [comment]
Any updates on this? Currently whenever I add a secret I need to manually delete the secret and the csi pods (sometimes more than once) before the change sticks. This is a very rough experience, I would love to see it fixed 🙂

**Comment by aramase** [comment]
> Any updates on this? Currently whenever I add a secret I need to manually delete the secret and the csi pods (sometimes more than once) before the change sticks. This is a very rough experience, I would love to see it fixed 🙂

This will be included in the auto rotation feature that's being added for the next release v0.0.14.

**Comment by connor4312** [comment]
Sounds good. Since it's been a couple months now, do you have steps that I can use to force secrets to be refreshed in the meantime? It seems that even deleting the pods and secret now (or sometimes) doesn't cause the secret to be refreshed. This is super frustrating and makes it hard to use keyvault in AKS 🙁

**Comment by connor4312** [comment]
Ah, actually, in the case where deleting didn't work, it seems like the access policy on my keyvault had gone missing somehow. So that's my fault, but reliable steps to refresh secrets would still be appreciated!

**Comment by aramase** [comment]
@connor4312 Sure, I'll add a doc with the current limitation and will update that as in when we release the auto-rotation feature.

**Comment by aramase** [comment]
/close 

As changes will be part of #303

**Pull request closed without merging**
