### PR TITLE
release: update manifest and helm charts for v1.2.4

### PR DESCRIPTION
**Pull request by nilekhc**
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
The version needs to be updated https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/ac3abec0fc6ecb465ce1ce872b81926f92eec4d6/Makefile#L32-L33 and https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/ac3abec0fc6ecb465ce1ce872b81926f92eec4d6/docker/Makefile#L18

**Comment by nilekhc** [comment]
> The version needs to be updated
> 
> https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/ac3abec0fc6ecb465ce1ce872b81926f92eec4d6/Makefile#L32-L33
> 
> and
> https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/ac3abec0fc6ecb465ce1ce872b81926f92eec4d6/docker/Makefile#L18

Done.

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

/hold
(for cherrypick to be merged to release branch)

**Pull request merged**
