### PR TITLE
feat: adds support for inplace upgrade test

### LINKED ISSUE #739: Add inplace upgrade test
We are removing workload resources while performing upgrade tests. Add inplace upgrade tests to validate behaviour without deleting existing resources.

Ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/602#discussion_r710258200

/assign

### PR DESCRIPTION
**Pull request by nilekhc**
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>

**What this PR does / why we need it**:
This PR adds support for inplace upgrade test with e2e-provider

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #739 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by nilekhc** [comment]
/hold

for https://github.com/kubernetes/test-infra/pull/23660

**Review by aramase — COMMENTED** [review]
/approve

**Pull request merged**
