### PR TITLE
helm: add podLabels parameter

### PR DESCRIPTION
**Pull request by t3mi**
**What this PR does / why we need it**:
Adds configuration for additional pod labels, like `CostCenter=IT`

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aramase** [comment]
`/test pull-secrets-store-csi-driver-image-scan` is dependent on #441, so should be fine for this PR

**Review by aramase — COMMENTED** [review]
@t3mi Could you also add the empty values `podLabels: {}` to the [values](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/manifest_staging/charts/secrets-store-csi-driver/values.yaml) file?

**Comment by t3mi** [comment]
@aramase sure, added.

**Comment by aramase** [comment]
@t3mi Thanks for updating. Could you also squash the commits?

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
