### PR TITLE
set gcr_cloud_build for buildx

### PR DESCRIPTION
**Pull request by aramase**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by claudiubelu** [comment]
I wonder if it's ok to call ``gcr_cloud_build`` twice. And putting it in the build script would mean that people trying to build and push that image to a different registry than gcr.io would be inconvenienced. I wonder if we can't put it in the ``cloudbuild.yaml``, like here: https://github.com/kubernetes/kubernetes/blob/master/build/pause/cloudbuild.yaml

**Comment by aramase** [comment]
@claudiubelu Makes sense! Let me make that change.

**Comment by aramase** [comment]
@claudiubelu Updated, PTAL!

**Pull request merged**
