### PR TITLE
docs: Update helm README.md with linux crd image values

### PR DESCRIPTION
**Pull request by jmingtan**
**What this PR does / why we need it**:
Update the helm docs with linux crds image values. This is useful if anyone needs to override the repository location.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jmingtan** [comment]
signed cla

**Review by aramase — COMMENTED** [review]
@jmingtan Thank you for the PR. The changes are to be made in [manifest_staging](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/manifest_staging/charts/secrets-store-csi-driver) folder only. The changes will be promoted to `charts/` at the time of release. Could you make this this change in `manifest_staging` and remove it from the `charts` folder?

**Comment by jmingtan** [comment]
> @jmingtan Thank you for the PR. The changes are to be made in [manifest_staging](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/manifest_staging/charts/secrets-store-csi-driver) folder only. The changes will be promoted to `charts/` at the time of release. Could you make this this change in `manifest_staging` and remove it from the `charts` folder?

Done, thanks for the heads up

**Comment by aramase** [comment]
/retitle docs: Update helm README.md with linux crd image values
/label tide/merge-method-squash

**Review by aramase — COMMENTED** [review]
/ok-to-test

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
