### PR TITLE
chore: remove deprecated logic of invoking provider binary

### PR DESCRIPTION
**Pull request by aramase**
**What this PR does / why we need it**:
- Removes logic to driver-provider communication by using binary
- Removes version check implemented for provider binary
- Deprecates flags that'll be removed in future releases

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tam7t** [comment]
Feels good!

/lgtm

**Comment by aramase** [comment]
Test failed with 

```
# output: /usr/lib/bats/bats-exec-test: line 58: az: command not found
```

Retrying to check if it's a flake as we install the `azure` cli as part of the e2e

/test pull-secrets-store-csi-driver-e2e-azure

**Comment by aramase** [comment]
Had to rebase merge conflicts from other PRs. 

@tam7t Ready for another `lgtm` 😄

**Pull request merged**
