### PR TITLE
test: add e2e for `--filtered-watch-secret=false`

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**What this PR does / why we need it**:
- Adds test for `--filtered-watch-secret=false`

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by nilekhc — APPROVED** [review]
/lgtm

**Comment by tam7t** [comment]
To make sure I understand, `filteredWatchSecret=true` in the next release, but we want to make sure everything continues to work if everything is deployed with `filteredWatchSecret=false`?

Is there a targeted release where `filteredWatchSecret=false` will be unsupported?

**Comment by aramase** [comment]
> To make sure I understand, filteredWatchSecret=true in the next release, but we want to make sure everything continues to work if everything is deployed with filteredWatchSecret=false?

That's right!

> Is there a targeted release where filteredWatchSecret=false will be unsupported?

We'll make it unsupported in the release after. We'll deprecate the flag and remove it in future releases.

**Pull request merged**
