### PR TITLE
fix(helm/values) - default syncSecret.enable to false

### LINKED ISSUE #268: Update readme post next release
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
We should add the following:
- default value for `syncSecrets.enable` will be set to `false` after the next 2 releases (secure by default)
- update deployment instructions https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-sync-with-kubernetes-secrets to enable this feature

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

### PR DESCRIPTION
**Pull request by ritazh**
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>

**What this PR does / why we need it**:
Default `syncSecret.enable` to `false`

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #268 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
We haven't announced in the previous release that this is going to disabled by default. I think we should update the current release note with this and also add it to the next one before disabling it. WDYT?

**Comment by tam7t** [comment]
Yeah, I'm thinking we tag this for `v0.0.23` and in release notes of  `v0.0.22` say that its _actually_ going to happen in 23

**Comment by ritazh** [comment]
sg!

**Review by aramase — COMMENTED** [review]
@ritazh Could you rebase the PR when you get a chance?

**Review by aramase — COMMENTED** [review]
/lgtm

**Pull request merged**
