### PR TITLE
use docker for generating manifests

### LINKED ISSUE #221: Switch to using docker manifest for image push
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Switch to using docker manifest for image push as the current image push job fails due to auth with manifest tool. 

```
time="2020-06-03T22:06:23Z" level=fatal msg="V2 registry PUT of manifest list failed: Put https://gcr.io/v2/k8s-staging-csi-secrets-store/driver/manifests/v0.0.11: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication"
```

We can generate the docker manifest and push using `docker manifest`

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

### PR DESCRIPTION
**Pull request by aramase**
**What this PR does / why we need it**:

Using `docker manifest` to generate image manifests and push. Tested with image `aramase/secrets-store-csi:buildx00`.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #221 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by claudiubelu** [comment]
``docker manifest create`` was the first thing I've tried too. I really wished it was ok, it would have been simpler. :)

The problem is that ``docker buildx`` doesn't set the ``os.version`` field for the Windows images that it builds, and then ``docker manifest create`` doesn't set those fields either, since it doesn't have any. Plus, ``docker manifest annotate`` doesn't allow you to set the ``os.version`` either, since it's using the manifest list v1 format for some reason.

That is why I was using ``manifest-tool``. It allowed me to set that ``os.version``. Without that ``os.version``, your manifest list can only support one version of Windows, since docker will pull the first one that matches the OS it's running on: windows/amd64. When there are multiple Windows images, it also looks at the ``os.version`` field to match the host OS version as closely as possible.

**Comment by aramase** [comment]
/close

The changes have been included in https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/225

**Pull request closed without merging**
