### PR TITLE
Add priorityClassName to daemonsets.

### PR DESCRIPTION
**Pull request by derek-burdick**
**What this PR does / why we need it**:
This PR adds provides the option to add a priorityClassName to the PODS. In some environments, pods with a higher priority set can preempt this pod and cause issues with the driver. This also allows the scheduler to preempt lower priority pods if this pod needs to be recreated.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by derek-burdick** [comment]
CLA signed

**Review by aramase — COMMENTED** [review]
@derek-burdick Thank you for the PR!

Could you make these changes only in [manifest_changing/charts](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/manifest_staging/charts/secrets-store-csi-driver) dir instead of charts dir? The chart changes are stored in the staging dir and move to charts during the release.

**Comment by derek-burdick** [comment]
@aramase  Moved to manifest_staging.

**Review by aramase — COMMENTED** [review]
@derek-burdick Could you also add the new values to the configuration table [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/manifest_staging/charts/secrets-store-csi-driver#configuration)

**Comment by derek-burdick** [comment]
@aramase Should I add the default value ("") to the values.yaml file as well?

**Review by aramase — COMMENTED** [review]
/lgtm

**Pull request merged**
