### PR TITLE
docs: add Akeyless as a Provider

### PR DESCRIPTION
**Pull request by netserheruty**
see more at: https://docs.akeyless.io/docs/kubernetes-secrets-store-csi-provider

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

### CODE REVIEW

**Comment by aramase** [comment]
/retitle docs: add Akeyless as a Provider

**Review by aramase — CHANGES_REQUESTED** [review]
Thank you for the PR @netserheruty! 

Could you follow the [steps](https://github.com/kubernetes/community/blob/master/CLA.md) to sign the CLA?

**Comment by akljph** [comment]
@aramase - I had a look at the EasyCLA and we are having some issues getting that sorted because I believe we have 2 different LF profiles for our company (AKEYLESS and Akeyless Security Ltd.). There's also an issue getting approval from the person in our organization who is supposed to be able to approve it. Any help there is appreciated.

Jeremy

**Comment by aramase** [comment]
Closing in favor of https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/1306

**Pull request closed without merging**
