### PR TITLE
chore: add the vendor directory

### LINKED ISSUE #668: Optimize driver build time for multi arch/os images
The binary is built inside the golang builder docker container. In case of prow image build in gcb, it takes ~1h10m for the image build to complete (linux/amd64, linux/arm64, windows/amd64/1809, windows/amd64/1903, windows/amd64/1909, windows/amd64/2004). 

We can optimize this by building the binary once on host for different os/arch and load into the docker image.

/assign

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**What this PR does / why we need it**:
- Adds the vendor directory. Generated by running `go mod vendor`
- Updates `go build` and `go test` to use vendor

Testing the build time difference using `cloud-build-local`

Difference between my dev machine and prow build instance:
```
2021/08/09 21:23:33 Warning: The server docker version installed (20.10.8) is different from the one used in GCB (19.03.8)
```

1. Without vendor
```
cloud-build-local --config=docker/cloudbuild.yaml --dryrun=false --push .  2.25s user 1.09s system 0% cpu 26:20.42 total
```
2. With vendor
```bash
cloud-build-local --config=docker/cloudbuild.yaml --dryrun=false --push .  2.25s user 1.09s system 0% cpu 19:22.83 total
```

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #668 

**Special notes for your reviewer**:

When updating the version of package:
1. Update the version in `go.mod`
2. Run `make vendor`

### CODE REVIEW

**Comment by aramase** [comment]
/hold 

for reviews

**Comment by nilekhc** [comment]
@aramase Could we add metrics around this? For eg what is the build time now vs what was earlier? It will be a good reference for future.

**Comment by aramase** [comment]
> @aramase Could we add metrics around this? For eg what is the build time now vs what was earlier? It will be a good reference for future.

Added the time difference I'm observing with `cloud-build-local` in the PR description.

**Comment by aramase** [comment]
We bumped the machine type used in cloudbuild as part of https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/714. With this change, the build time has significantly improved. It now takes 14m instead of the previous 1h10m.

/close

**Pull request closed without merging**
