### PR TITLE
add tam7t as approver

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**What this PR does / why we need it**:
Thank you for all the contributions so far @tam7t! 

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The criteria for membership is documented in [Secrets Store CSI Driver Membership](https://docs.google.com/document/d/1YqFVTJdxvNXhXkWogYf7AOKMnUjPFHCPuYtTgJSHohU/edit?usp=sharing)

### CODE REVIEW

**Comment by aramase** [comment]
/hold

Putting a hold for comments from others in the community

**Comment by nilekhc** [comment]
+1

**Comment by ritazh** [comment]
+1  🎉 

@tam7t Thank you for all your ongoing contributions to this project and the community!

**Comment by sozercan** [comment]
+1 🎉

**Pull request merged**
