### PR TITLE
Add AWS Provider

### PR DESCRIPTION
**Pull request by nlamirault**
https://aws.amazon.com/fr/blogs/security/how-to-use-aws-secrets-configuration-provider-with-kubernetes-secrets-store-csi-driver/

**What this PR does / why we need it**:

Add the AWS Provider link

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
@nlamirault Thank you for the PR. For being added to the supported providers list, the 1st step would be to add e2e tests for the provider. Then we can add the provider to the list of supported providers.

Here is the doc: https://secrets-store-csi-driver.sigs.k8s.io/providers.html

**Review by aramase — COMMENTED** [review]
Now that the AWS e2e tests PR is merged, we should be able to get this in. Could you also add the AWS provider to the section [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/book/src/concepts.md#provider-for-the-secrets-store-csi-driver)

**Comment by tam7t** [comment]
I think we were also going to block this on:
* https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/12
* https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/7

**Review by lasred — APPROVED** [review]

**Review by aramase — COMMENTED** [review]
@nlamirault Gentle ping! Could you also add the AWS provider to the section [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/book/src/concepts.md#provider-for-the-secrets-store-csi-driver) as part of this PR?

**Review by aramase — COMMENTED** [review]
/approve

**Pull request merged**
