### PR TITLE
helm: add tolerations to helm charts

### LINKED ISSUE #227: Add tolerations to helm charts
/kind feature

### PR DESCRIPTION
**Pull request by fernandosilvacornejo**
**What this PR does / why we need it**:
Add tolerations as an optional helm chart value for Linux and Windows daemon sets.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #227 

**Special notes for your reviewer**:
Not sure if tests are required, or if this justifies upgrading the chart version. Please let me know and I'll update!

### CODE REVIEW

**Comment by aramase** [comment]
@fernandosilvacornejo Thank you for the PR! As part of #258 we have created a new `manifest_staging` dir that'll host the chart/yaml updates. This is done so the manifest updates are part of a tagged release. Can you update the PR to add the changes in here - [manifest_staging/charts](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/manifest_staging/charts/secrets-store-csi-driver)

**Comment by fernandosilvacornejo** [comment]
@aramase updated! I noticed that the `metricsAddr` parameter is also missing from the `manifest_staging` folder. Should I add it as well or is someone else into that?

**Comment by aramase** [comment]
@aramase updated! I noticed that the metricsAddr parameter is also missing from the manifest_staging folder. Should I add it as well or is someone else into that?

> @fernandosilvacornejo Good catch! Yes, please add that to the `manifest_staging` dir. For this PR, we only need to update `manifest_staging/chart` dir. When we cut a release we'll update the `charts` dir with all the manifests from here.

**Comment by fernandosilvacornejo** [comment]
@aramase restored original `charts` folder and added the `metricsAddr` parameter to the staging manifests 👍

**Pull request merged**
