### PR TITLE
chore: update to go 1.16

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

**What this PR does / why we need it**:
- Update to go 1.16
- Migrate from deprecated `io/ioutil` package to using `os` or `io` (https://golang.org/doc/go1.16#ioutil)

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by aramase** [comment]
/hold

Need to wait for kubekins image to be updated with go1.16

**Review by sozercan — APPROVED** [review]

**Comment by aramase** [comment]
> Need to wait for kubekins image to be updated with go1.16

Kubekins image has been updated with go 1.16. This PR is now ready for review and merge.

/hold cancel

**Pull request merged**
