### PR TITLE
fix: increase hook-weight for crd upgrade jobs in helm charts

### LINKED ISSUE #967: Helm chart upgrade fails because Job runs before ServiceAccount creation
**What steps did you take and what happened:**

During the upgrade of helm chart 0.2.0 to 1.1.2:
```
% helm upgrade secrets-store-csi secrets-store-csi-driver/ --namespace kube-system --debug
upgrade.go:142: [debug] preparing upgrade for secrets-store-csi
upgrade.go:521: [debug] copying values from secrets-store-csi (v1) to new release.
upgrade.go:150: [debug] performing update for secrets-store-csi
upgrade.go:322: [debug] creating upgraded release for secrets-store-csi
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ServiceAccount
client.go:328: [debug] serviceaccounts "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ClusterRole
client.go:328: [debug] clusterroles.rbac.authorization.k8s.io "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ClusterRoleBinding
client.go:328: [debug] clusterrolebindings.rbac.authorization.k8s.io "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-driver-keep-crds" Job
client.go:328: [debug] jobs.batch "secrets-store-csi-driver-keep-crds" not found
client.go:128: [debug] creating 1 resource(s)
client.go:529: [debug] Watching for changes to Job secrets-store-csi-driver-keep-crds with timeout of 5m0s
client.go:557: [debug] Add/Modify event for secrets-store-csi-driver-keep-crds: ADDED
client.go:596: [debug] secrets-store-csi-driver-keep-crds: Jobs active: 0, jobs failed: 0, jobs succeeded: 0

% kubectl -n kube-system get events --sort-by='{.lastTimestamp}'
2m45s       Warning   FailedCreate        job/secrets-store-csi-driver-upgrade-crds
Error creating: pods "secrets-store-csi-driver-upgrade-crds--1-" is forbidden: error looking up service account kube-system/secrets-store-csi-secrets-store-csi-driver-upgrade-crds: serviceaccount "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" not found
```

**What did you expect to happen:**
The Secrets Store CSI Driver is getting deployed to the cluster.

**Anything else you would like to add:**
Job resource from [/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/a5b207f5904874b20e00aa29416dda4e4162e2b2/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml#L81) and [/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/a5b207f5904874b20e00aa29416dda4e4162e2b2/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml#L81) should have higher hook-weight (lower priority) than other resources like ClusterRole, ClusterRoleBinding, ServiceAccount, PodSecurityPolicy.

Now they have the same hook-weight and therefore Job is starting before ServiceAccount _secrets-store-csi-secrets-store-csi-driver-upgrade-crds_ creation.

**Which provider are you using:**
AWS EKS 1.22

**Environment:**

- Secrets Store CSI Driver version: k8s.gcr.io/csi-secrets-store/driver:v1.1.2
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### PR DESCRIPTION
**Pull request by david1155**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Helm chart upgrade fails because of the incorrect hook-weight.

Job resource from [/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/a5b207f5904874b20e00aa29416dda4e4162e2b2/charts/secrets-store-csi-driver/templates/crds-upgrade-hook.yaml#L81) and [/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/a5b207f5904874b20e00aa29416dda4e4162e2b2/charts/secrets-store-csi-driver/templates/keep-crds-upgrade-hook.yaml#L81) should have higher hook-weight (lower priority) than other resources like ClusterRole, ClusterRoleBinding, ServiceAccount, PodSecurityPolicy.

They have the same hook-weight and therefore Job is starting before ServiceAccount secrets-store-csi-secrets-store-csi-driver-upgrade-crds creation.

This PR increases the hook-weight for the Job resource. Therefore Job resource will be created after corresponding ServiceAccount.

**Which issue(s) this PR fixes**:
Fixes #967

**Special notes for your reviewer**:
After changing Job weight to "10" for crds-upgrade-hook.yaml and "20" for keep-crds-upgrade-hook.yaml, the chart was successfully upgraded:
```
% helm upgrade secrets-store-csi . --namespace kube-system --debug
upgrade.go:142: [debug] preparing upgrade for secrets-store-csi
upgrade.go:521: [debug] copying values from secrets-store-csi (v1) to new release.
upgrade.go:150: [debug] performing update for secrets-store-csi
upgrade.go:322: [debug] creating upgraded release for secrets-store-csi
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ServiceAccount
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ClusterRole
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ClusterRoleBinding
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-keep-crds" ServiceAccount
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-keep-crds" ClusterRole
client.go:328: [debug] clusterroles.rbac.authorization.k8s.io "secrets-store-csi-secrets-store-csi-driver-keep-crds" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-keep-crds" ClusterRoleBinding
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "secrets-store-csi-driver-keep-crds" Job
client.go:128: [debug] creating 1 resource(s)
client.go:529: [debug] Watching for changes to Job secrets-store-csi-driver-keep-crds with timeout of 5m0s
client.go:557: [debug] Add/Modify event for secrets-store-csi-driver-keep-crds: ADDED
client.go:596: [debug] secrets-store-csi-driver-keep-crds: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for secrets-store-csi-driver-keep-crds: MODIFIED
client.go:299: [debug] Starting delete for "secrets-store-csi-driver-upgrade-crds" Job
client.go:128: [debug] creating 1 resource(s)
client.go:529: [debug] Watching for changes to Job secrets-store-csi-driver-upgrade-crds with timeout of 5m0s
client.go:557: [debug] Add/Modify event for secrets-store-csi-driver-upgrade-crds: ADDED
client.go:596: [debug] secrets-store-csi-driver-upgrade-crds: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:557: [debug] Add/Modify event for secrets-store-csi-driver-upgrade-crds: MODIFIED
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ServiceAccount
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ClusterRole
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-upgrade-crds" ClusterRoleBinding
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-keep-crds" ServiceAccount
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-keep-crds" ClusterRole
client.go:299: [debug] Starting delete for "secrets-store-csi-secrets-store-csi-driver-keep-crds" ClusterRoleBinding
client.go:299: [debug] Starting delete for "secrets-store-csi-driver-keep-crds" Job
client.go:299: [debug] Starting delete for "secrets-store-csi-driver-upgrade-crds" Job
client.go:218: [debug] checking 7 resources for changes
client.go:510: [debug] Patch ServiceAccount "secrets-store-csi-driver" in namespace kube-system
client.go:239: [debug] Created a new ClusterRole called "secretproviderclasses-admin-role" in 

client.go:239: [debug] Created a new ClusterRole called "secretproviderclasses-viewer-role" in 

client.go:510: [debug] Patch ClusterRole "secretproviderclasses-role" in namespace 
client.go:501: [debug] Looks like there are no changes for ClusterRoleBinding "secretproviderclasses-rolebinding"
client.go:510: [debug] Patch DaemonSet "secrets-store-csi-secrets-store-csi-driver" in namespace kube-system
client.go:501: [debug] Looks like there are no changes for CSIDriver "secrets-store.csi.k8s.io"
upgrade.go:157: [debug] updating status for upgraded release for secrets-store-csi
Release "secrets-store-csi" has been upgraded. Happy Helming!
```

### CODE REVIEW

**Comment by nilekhc** [comment]
/lgtm
/hold 
for others to review

**Review by aramase — COMMENTED** [review]
@david1155 Thanks for the PR! 

/retitle fix: increase hook-weight for crd upgrade jobs in helm charts
/approve

**Pull request merged**
