### PR TITLE
test: add test for view and admin cluster role

### PR DESCRIPTION
**Pull request by anapsix**
As a follow-up to  #836, adding simple tests to verify the new
aggregation roles are applied

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
Thanks for the PR! The cluster roles don't need to be duplicated for e2e but rather we want to validate the file in `manifest_staging`. You can add the deploy commands here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/d32ca72038650c79561092dab26bf6d5a9c9e40a/Makefile#L403-L408

**Comment by aramase** [comment]
/test: add test for view and admin cluster role

**Comment by aramase** [comment]
/retitle test: add test for view and admin cluster role

**Comment by anapsix** [comment]
Thanks @aramase, done!

**Review by aramase — COMMENTED** [review]
/lgtm

**Comment by anapsix** [comment]
Should I the same tests to the `test/bats/vault.bats`?

**Comment by aramase** [comment]
> Should I the same tests to the test/bats/vault.bats?

No, just `e2e-provider` is sufficient. Eventually we'll be trimming the provider tests to include basic provider validation only.

**Pull request merged**
