### PR TITLE
helm: additional cluster roles for secretproviderclasses

### LINKED ISSUE #835: missing aggregation ClusterRoles for SecretProviderClasses
**Describe the solution you'd like**
At the moment, there are no ClusterRoles created for SecretProviderClasses resources with aggregation to `view` and `admin` default roles. This prevents `ClusterRole/admin` and `ClusterRole/view` from accessing SecretProviderClasses resources.

It would be helpful to create a default roles with admin and view permissions, taking advantage of [aggregation functionality](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) to update default RBAC roles.

### PR DESCRIPTION
**Pull request by anapsix**
**What this PR does / why we need it**:
At the moment, there are no ClusterRoles created for SecretProviderClasses resources with aggregation to view and admin default roles. This prevents ClusterRole/admin and ClusterRole/view from accessing SecretProviderClasses resources.

**Which issue(s) this PR fixes**:
Fixes #835

### CODE REVIEW

**Comment by anapsix** [comment]
Actually, in kubernetes-sigs/secrets-store-csi-driver#836 I've used `secretproviderclasses-admin-role` and `secretproviderclasses-viewer-role`.
@jalaziz , should I use the same names here, do you think?

**Review by aramase — COMMENTED** [review]
@anapsix Thank you for the PR.

Please update the yamls in the [manifest_staging/](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/manifest_staging/) folder, where we host the staging charts and deployment yamls. All the yaml changes will then be promoted into the released charts folder (`charts/`) with the next release.

**Comment by aramase** [comment]
/retitle helm: additional cluster roles for secretproviderclasses

**Comment by anapsix** [comment]
> @anapsix Thank you for the PR.
> 
> Please update the yamls in the [manifest_staging/](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/manifest_staging/) folder, where we host the staging charts and deployment yamls. All the yaml changes will then be promoted into the released charts folder (`charts/`) with the next release.

I believe I did @aramase. Please clarify if I should remove changes to manifest templates in `charts/secrets-store-csi-driver/templates/` in favor of `manifest_staging/charts/secrets-store-csi-driver/templates/`?

**Comment by aramase** [comment]
> I believe I did @aramase. Please clarify if I should remove changes to manifest templates in charts/secrets-store-csi-driver/templates/ in favor of manifest_staging/charts/secrets-store-csi-driver/templates/?

that's right! the changes are only made in `manifest_staging`. So you would need to remove the changes from `charts/secrets-store-csi-driver/templates/`.

**Comment by anapsix** [comment]
Roger that, @aramase. Thanks for the clarification. Done.

**Comment by tam7t** [comment]
I think this is good but we'd probably also want to add something for the `manifest_staging/deploy/` so that they could be added with just the `kubectl apply -f deploy/*` in the future. (we can do that as a separate PR)

/lgtm

**Comment by anapsix** [comment]
> I think this is good but we'd probably also want to add something for the `manifest_staging/deploy/` so that they could be added with just the `kubectl apply -f deploy/*` in the future. (we can do that as a separate PR)
> 
> /lgtm

@tam7t, added the new ClusterRoles to the `manifest_staging/deploy`. Please let me know if I did not do it the way you've expected.

**Comment by anapsix** [comment]
Also, should I add the manifests to `test/bats/tests/e2e_provider/`?
And the following to the `Test rbac roles and role bindings exist` test in `test/bats/e2e-provider.bats`?:
```sh
  run kubectl get clusterrole/secretproviderclasses-admin-role
  assert_success

  run kubectl get clusterrole/secretproviderclasses-viewer-role
  assert_success
```

**Comment by tam7t** [comment]
Thanks! And yeah adding a case for `test/bats/tests/e2e_provider` would be great as a sanity check that the roles apply successfully

**Review by aramase — COMMENTED** [review]
/approve

**Comment by anapsix** [comment]
> Thanks! And yeah adding a case for `test/bats/tests/e2e_provider` would be great as a sanity check that the roles apply successfully

eh.. too late, tam7t .. sorry I didn't make in time before the merge
Btw, wouldn't make more sense to symlink some of those e2e manifest to the ones in manifest_staging?

**Pull request merged**
