### PR TITLE
release: update manifest and helm charts for v1.4.6

### PR DESCRIPTION
**Pull request by nilekhc**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

update manifest and helm charts for `v1.4.6`

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

/assign @aramase

### CODE REVIEW

**Comment by nilekhc** [comment]
/retitle release: update manifest and helm charts for v1.4.6

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

/hold
(for `v1.4.6` tag to be cut)

**Comment by aramase** [comment]
/hold cancel

https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.4.6 is published!

**Pull request merged**
